yaml
Copy code
# .github/workflows/python-app.yml
name: CI Pipeline

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    -name: Run script
     run: python main.py # Run the main.py script

    -name: Run tests
     run: test_main.py # Run tests in test_main.py 

  
        
